compressionLevel: mixed

enableGlobalCache: true

nmMode: hardlinks-local

nodeLinker: node-modules

npmAuthToken: "${NPM_TOKEN:-NONE}"

npmPublishAccess: public

npmPublishRegistry: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.3.1.cjs

# 如果需要设置 HTTPS 代理
httpsProxy: "http://127.0.0.1:7890"
